### ISSUE TITLE
Mac uname issue

### ISSUE THREAD

**Issue by den-vasyliev** [bartaadalbert/leaks#1]
`➜  kbot git:(main) ✗ curl -sSfL https://raw.githubusercontent.com/bartaadalbert/leaks/master/gitleaks.sh | bash -s

uname: illegal option -- o
usage: uname [-amnprsv]
This script must be run as administrator or with elevated privileges.
➜  kbot git:(main) ✗ sudo curl -sSfL https://raw.githubusercontent.com/bartaadalbert/leaks/master/gitleaks.sh | bash -s

Password:
uname: illegal option -- o
usage: uname [-amnprsv]
This script must be run as administrator or with elevated privileges.`

**Comment by bartaadalbert** [comment]
Previously, you may have seen a message saying "This script must be run as administrator or with elevated privileges." This was caused by a check for administrator privileges that was incompatible with certain systems.
In the latest version of the script, i have commented out this check, allowing the script to be executed without any issues. The script should now work seamlessly across different environments.
Additionally, for macOS users, there is an important note. macOS may block scripts from running if they are from an unidentified developer. In case you encounter a warning about the script being from an unidentified developer, you can allow it by going to System Preferences -> Security & Privacy and choose to open it anyway.

I encourage you to download the updated script and let me know if you face any issues. Your feedback is invaluable to me, and I greatly appreciate your contribution to improving this script.

Thank you for your  support.

**Comment by den-vasyliev** [comment]
Thanks for the reply. Fixed but got another issue:
`➜  kbot git:(main) ✗ curl -sSfL https://raw.githubusercontent.com/bartaadalbert/leaks/master/gitleaks.sh | bash -s

The issue with administrator privileges has been fixed. You were seeing the message because the script was checking for administrator privileges in an incompatible manner. It's now been commented out and the script should work without any issues.
Pre-commit hook is already installed. Removing it...
Pre-commit hook removed successfully.
➜  kbot git:(main) ✗ curl -sSfL https://raw.githubusercontent.com/bartaadalbert/leaks/master/gitleaks.sh | bash -s

The issue with administrator privileges has been fixed. You were seeing the message because the script was checking for administrator privileges in an incompatible manner. It's now been commented out and the script should work without any issues.
Pre-commit hook is not installed. Installing it...
Pre-commit hook installed successfully.
➜  kbot git:(main) ✗ git commit -am 'fmt'                  
.git/hooks/pre-commit: line 45: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
.git/hooks/pre-commit: line 51: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
.git/hooks/pre-commit: line 55: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
Gitleaks not found, will be install...
Temporary directory created at: ./temp_dir 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2708k  100 2708k    0     0  2667k      0  0:00:01  0:00:01 --:--:-- 8427k
Gitleaks is enabled. Running gitleaks...`

**Comment by den-vasyliev** [comment]
Non idempotent with` Pre-commit hook is already installed. Removing it...`

**Comment by bartaadalbert** [comment]
Thank you for taking the time to evaluate the script and providing your valuable feedback.

I understand your concern regarding the non-idempotent behavior of the script. When the script is executed, it checks if the pre-commit hook is already installed. If it's already installed, the script removes it, and if it's run again, it reinstalls it. This behavior was designed to provide an option for users to easily remove and reinstall the hook as needed.

However, I also understand that this behavior might not be what some users expect. One solution I am considering is to add parameters to the script. For example, the script could be executed with a parameter like --install-- or --uninstall-- to either install or remove the pre-commit hook respectively.

Would this approach address your concern? I would love to know your thoughts on this.

**Comment by den-vasyliev** [comment]
The default bash on macOS is still bash v3. 
`declare -A i`s for v5
so i change to`declare -a ` and all works fine now.
thanks!
